### ISSUE TITLE
Error: Cannot find module 'prismjs/themes/prism-solarized-light.css''

### ISSUE THREAD

**Issue by asnunes** [mAAdhaTTah/babel-plugin-prismjs#101]
In README.md file, PrismJS themes should be specified using kebab-case form:

````md
theme: Name of theme to include in the bundle. Themes can be found here. Use lower-kebab-case for the theme name, e.g. solarized-light.
`````

So, for solarized light theme, plugin definition should be like

````js
      [
        "prismjs",
        {
          languages: [
            "javascript",
            "shell",
            "css",
          ],
          plugins: ["line-numbers"],
          theme: "solarized-light",
          css: true,
        },
      ],
````

But, when trying to load "solarized-light" as said, I got the follow error message on Chrome console:

````
Error: Cannot find module 'prismjs/themes/prism-solarized-light.css'
````

A similar error occur when trying to load 'tomorrow-night' theme. In "node_modules/prismjs/themes", "solarized-light" is named as `prism-solarizedlight.css` and "tomorrow-night" is just `prism-tomorrow.css`.

So, In order to load theme correctly I typed "solarizedlight" or "tomorrow" on theme definition instead of "solarized-light" or "tomorrow-night". Is this kebab-case pattern incorrect or I am doing something wrong?   

Thanks!

**Comment by mAAdhaTTah** [comment]
Yeah, the themes in the PrismJS repo are here: https://github.com/PrismJS/prism/tree/master/themes

The `default` theme is special cased in the babel plugin but otherwise, the slug of the theme needs to match the slug after `prism-` in the repo.

That said, it looks like the docs are wrong, so I'll fix that.

**Comment by hemmingson** [comment]
This issue has already fixed by this [pull request](https://github.com/mAAdhaTTah/babel-plugin-prismjs/pull/217/commits/6090fecbf230ee971d93c85d8e22d89888f5ca57).
