### ISSUE TITLE
Support for custom themes

### ISSUE THREAD

**Issue by GriffinJohnston** [mAAdhaTTah/babel-plugin-prismjs#116]
Is there any way to add themes from https://github.com/PrismJS/prism-themes using this plugin? Or maybe custom definitions? The defaults are really pretty limited.

**Comment by mAAdhaTTah** [comment]
Not currently, but you can import it yourself outside of the configuration as a stopgap in the meantime.

**Comment by GriffinJohnston** [comment]
Got it. Thanks the quick reply!

**Comment by mAAdhaTTah** [comment]
Only a year late, but see #234 for the incoming implementation.
