### ISSUE TITLE
Dependencies are in the wrong order

### ISSUE THREAD

**Issue by blastrock** [mAAdhaTTah/babel-plugin-prismjs#19]
When using the following list:

```js
          languages: [
            'clike',
            'bash',
            'cpp',
            'go',
            'java',
            'javascript',
            'json',
            'kotlin',
            'shell',
            'objectivec',
            'swift',
          ],
```

The final list is:

```js
[ 'java',
  'clike',
  'c',
  'cpp',
  'go',
  'bash',
  'javascript',
  'json',
  'kotlin',
  'objectivec',
  'swift' ]
```

which is broken because java depends on clike.

I don't know why peerDependencies is used to order dependencies, but it seems like it works better with requires.

Related: #3

**Comment by mAAdhaTTah** [comment]
Thanks for the bug report. `peerDependencies` are used because components modify their peers, so the peers need to be loaded first so they can be modified.

**Comment by mAAdhaTTah** [comment]
Just pubbed v1.1.1, which should resolve this.

**Comment by blastrock** [comment]
Thanks for the quick response and the explanation!

1.1.1 does fix the issue I opened, however this new list breaks it:

```js
          languages: [
    "bash",
    "cpp",
    "go",
    "java",
    "javascript",
    "json",
    "kotlin",
    "shell",
    "objectivec",
    "swift"
          ],
```

It is the same list as before, but without "clike". It produces the following sorted list:

```js
[ 'java',
  'bash',
  'c',
  'cpp',
  'go',
  'clike',
  'javascript',
  'json',
  'kotlin',
  'objectivec',
  'swift' ]
```

which is broken for the same reason: java depends on clike.

We use node v10.15.2 which is < 12 as you guessed.
