### ISSUE TITLE
Can't load line-highlight plugin

### ISSUE THREAD

**Issue by MieszkoWrzeszczynski** [mAAdhaTTah/babel-plugin-prismjs#21]
Despite the fact that I've added 'line-highlight' to the plugins array Prism object doesn't contain it. 

My webpack config:
```
  'languages': ['r'],
  'plugins': ['line-numbers', 'line-highlight']
```
Prism plugins object:
```
"{"lineNumbers":{}}"
```

**Comment by mAAdhaTTah** [comment]
It wouldn't; [line-highlight])https://github.com/PrismJS/prism/blob/master/plugins/line-highlight/prism-line-highlight.js) doesn't modify the Prism object that way.
