### ISSUE TITLE
Cannot find .babelrc file

### ISSUE THREAD

**Issue by matteioo** [mAAdhaTTah/babel-plugin-prismjs#270]
Hello everybody,

I've installed this plugin in order to bundle my PrismJS (because every language got highlighted except `language-c`) using `npm install babel-plugin-prismjs` but I can't find the `.babelrc`-file. Do I need to create the file?

Thank you in advance.

**Comment by mAAdhaTTah** [comment]
Yes, Babel has a great walkthrough for configuring it [here](https://babeljs.io/setup).
