### ISSUE TITLE
Use peerDependencies to ensure correct load order

### ISSUE THREAD

**Issue by mAAdhaTTah** [mAAdhaTTah/babel-plugin-prismjs#3]

**Comment by RunDevelopment** [comment]
What about plugins?
They have `after` properties to ensure a correct load order. I assume that they should be dealt with as well?

**Comment by mAAdhaTTah** [comment]
Yeah, those aren't currently handled either.

**Comment by EryouHao** [comment]
What is the progress of this matter?
