### ISSUE TITLE
Missing support for aliases

### ISSUE THREAD

**Issue by chemicalbr** [mAAdhaTTah/babel-plugin-prismjs#4]
Cannot read property 'require' of undefined
    at getRequire (/Users/emiltsokov/Work/Cobalt-Website/website/Local/src/wp-content/themes/cobalt-guidelines/assets/node_modules/babel-plugin-prismjs/lib/getComponents.js:25:42)

**Comment by mAAdhaTTah** [comment]
In the short-term, use `markup` as the language.

In the long-term, we probably need to search the components.json object if any language's alias matches.

**Comment by jmau111** [comment]
found something that kinda work : 

`
{
  "plugins": [
  	["@babel/plugin-proposal-class-properties"],
    ["prismjs", {
        "languages": ["markup", "javascript", "php", "git", "sql", "bash"],
        "theme": "funky",
        "css": true
    }
    ]
  ]
}
`
