### ISSUE TITLE
In the short-term, use `markup` as the language.

### ISSUE THREAD

**Issue by FreemenL** [mAAdhaTTah/babel-plugin-prismjs#5]
In the short-term, use `markup` as the language.

In the long-term, we probably need to search the components.json object if any language's alias matches.

_Originally posted by @mAAdhaTTah in https://github.com/mAAdhaTTah/babel-plugin-prismjs/issues/4#issuecomment-452833584_

**Comment by mAAdhaTTah** [comment]
If this is a real issue, feel free to reopen, but not sure what happened here.
