### ISSUE TITLE
Can't resolve 'prism-al', 'prism-hlsl', 'prism-iecst' ...

### ISSUE THREAD

**Issue by AM-77** [mAAdhaTTah/babel-plugin-prismjs#89]
When trying to use all the languages from [the languages-list](https://prismjs.com/#languages-list).
this error occurs `Can't resolve 'prism-al'`
Its seems that the files `prism-al`, `prism-hlsl`, `prism-iecst` and maybe others, does not exist in the `prismjs/components` folder

**Comment by RunDevelopment** [comment]
The languages on the Prism website are the ones that are currently in [master](https://github.com/PrismJS/prism). They will be available with the next PrismJS release (maybe in a few weeks).
